---
title: "Bruna Lab Fieldwork Checklist"
date: "updated: `r Sys.Date()`"
header-includes:
- \AtBeginDocument{\let\maketitle\relax} # this removes default title section
- \usepackage[default]{sourcesanspro}
- \usepackage{fancyhdr} # modify header into left, center, right
- \pagestyle{fancy} # cues the use of fancy headers
- \fancyfoot{} # cues the use of fancy footer
- \renewcommand{\footrulewidth}{0.4pt}% default is 0pt
# month & year on header right
- \setlength{\headheight}{14.49998pt}
- \fancyhead[R]{Last update `r format(Sys.time(), '%d %B %Y')`}
- \fancyhead[L]{Fieldwork Checklists, p. \thepage} 
- \fancyfoot[R]{Download or suggest improvments at the {\href{https://github.com/BrunaLab/research_trip_checklists.git}{Bruna Lab Github Repository}}\\}
# - \usepackage{setspace}{singlespace} # manipulate line spacing 
- \usepackage{parskip} # manipulate indents and spacing before/after paragra phs 
- \usepackage{xcolor} # changes colors of text
# to center to top level (#) headings (my name) and change color of font
# more info # https://www.ctan.org/pkg/sectsty
- \usepackage{sectsty} \sectionfont{\centering\color{darkmidnightblue}}
# to center to sub-sub-headings (###) and change color of font
- \usepackage{sectsty} \subsectionfont{\color{darkmidnightblue}}
# http://latexcolor.com/ to choose colors
# define the colors used above with rgb codes
- \definecolor{darkcerulean}{rgb}{0.03, 0.27, 0.49}
- \definecolor{darkmidnightblue}{rgb}{0.0, 0.2, 0.4}

mainfont: SourceSansPro
geometry: margin=1in
fontsize: 12pt
linkcolor: blue
urlcolor: blue
output: pdf_document
# html_document:
# df_print: paged
# rmdformats::robobook: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- To make your own template use the following as needed: -->
<!-- - [ ] Item -->
<!-- - [x] Item -->

source 

# Travel 

## Prior to Departure

- [ ] Inform bank & credit cards of travel dates
- [ ] Update emergency contact information 
- [ ] Provide trip details and contact info to emergency contacts
- [ ] verify vaccinations required for the region
- [ ] travel & emergency insurance 
- [ ] Register with US State Dept. [STEP](https://step.state.gov/) (for US citizens) or equivalent for citizens of other countries 

## Documents

- [ ] passport valid for duration of trip
- [ ] driver's license / international drivers license
- [ ] printout of tickets & boarding passes
- [ ] visa(s)
- [ ] Immunization Records
- [ ] copies of IACUC approval
- [ ] copies of IRB approval
- [ ] permits
    - [ ] research permits 
    - [ ] collection permits 
    - [ ] export permits 
    - [ ] import permits
- [ ] Prescriptions
    - [ ] Medications
    - [ ] Glasses
- [ ] Emergency Contact List
- [ ] Letter from host institutions

## Carry-on Items

- [ ] day pack 
- [ ] airplane pillow 
- [ ] book
- [ ] cash, debit / credit cards
- [ ] change of socks, underwear, t-shirt
- [ ] e-reader & charger
- [ ] universal adapter plug
- [ ] glasses / spare glasses
- [ ] glasses case
- [ ] gum 
- [ ] headphones
- [ ] KN95 masks
- [ ] laptop
- [ ] laptop case
- [ ] laptop charger 
- [ ] snacks
- [ ] phone 
- [ ] phone charger
- [ ] powerbank / portable battery
- [ ] Prescription medications (for the length of your stay)
- [ ] toothbrush
- [ ] toothpaste
- [ ] translation app
- [ ] wallet
- [ ] watch 
- [ ] water bottle
- [ ] sleep mask

## Toiletries

- [ ] birth control / protection
- [ ] contact lenses 
- [ ] contact solution
- [ ] deodorant 
- [ ] dramamine
- [ ] epipen
- [ ] hair products 
- [ ] Ibuprofen 
- [ ] female hygiene products
- [ ] shampoo / conditioner
- [ ] skincare products
- [ ] makeup
- [ ] soap / body wash
- [ ] sunscreen
- [ ] hair ties
- [ ] Antihistamines
- [ ] anti-bacterial cream
- [ ] anti-fungal cream
- [ ] OTC treatment for UTIs
- [ ] heat pad / muscle cream


## Clothing

- [ ] bandannas
- [ ] bathing suit
- [ ] clothing for town, social events
- [ ] pants
- [ ] rain jacket or poncho
- [ ] sandals / flip-flops
- [ ] shirts: long-sleeved for the field
- [ ] shorts
- [ ] socks
- [ ] sunglasses
- [ ] sweater/jacket
- [ ] swim goggles 
- [ ] swimsuit
- [ ] t-shirts
- [ ] tennis shoes
- [ ] towel
- [ ] underwear
- [ ] footwear for the field (e.g, hiking boots, rubber boots)
- [ ] hat

## On Arrival

- [ ] Purchase local cell phone / SIM card
- [ ] Exchange cash for local currency
- [ ] Registration with local authorities _(if required)_

## Travel with kids

- [ ] passport
- [ ] birth certificate
- [ ] marriage certificate
- [ ] Required documentation if minor child is traveling with only 1 parent
- [ ] immunization records

\newpage
# Fieldwork - General

- [ ] backpack
- [ ] AA batteries
- [ ] AAA batteries
- [ ] binoculars
- [ ] spotting scope
- [ ] books
- [ ] camera
- [ ] camera charger or batteries
- [ ] checklist (for field work)
- [ ] clipboard
- [ ] compass 
- [ ] machete
- [ ] safety whistle
- [ ] data sheets
- [ ] field guides
- [ ] duct tape
- [ ] field notebooks
- [ ] first aid kit (see [REI's list of recommended items](https://github.com/BrunaLab/research_trip_checklists/blob/8334720654ccf4ee78cd67d19379729dc52232b5/First-Aid_Kit_Checklist.pdf))
- [ ] games / playing cards
- [ ] GPS 
- [ ] headlamp / flashlight
- [ ] Insect repellent (Deet, Permethrin for pre-treating clothes)
- [ ] latex gloves
- [ ] laundry bags
- [ ] maps 
- [ ] memory cards
- [ ] mosquito net
- [ ] pencils
- [ ] sharpies
- [ ] flagging
- [ ] permits 
- [ ] pocket knife
- [ ] portable hard drive 
- [ ] rain cover for pack
- [ ] safety whistle
- [ ] snacks for field (e.g., granola, protein bars, sunflower seeds, almonds)
- [ ] treats or gmaes to play with kids 
- [ ] Ziploc bags

\newpage
# Fieldwork - Human Subjects 

- [ ] checklist for interviews
- [ ] IRB consent forms for interviews
- [ ] questionnaires 
- [ ] compensation for participants (gift cards, etc.) if approved
- [ ] digital audio recorder

\newpage
# Fieldwork - Botanical 

- [ ] pruners (Felco 4)
- [ ] pole pruners
- [ ] plant press
- [ ] whirl packs
- [ ] ethanol

\newpage
# Fieldwork - Entomological

- [ ] whirl packs
- [ ] ethanol
- [ ] pooter
- [ ] Extraction Tools
  - [ ] Winkler Kits
  - [ ] Berlese Funnels & Lights
- [ ] whirl packs
- [ ] ethanol


<!-- # Fieldwork - Specific Project -->

<!-- - [ ] Item 1 -->
<!-- - [ ] Item 2 -->
<!-- - [ ] Item 3 -->
